from graph import * 
def CreateGraph_1 (): 
    G = Graph() 
    AddNode(G, Node("A",1,20))
    AddNode(G, Node("B",8,17)) 
    AddNode(G, Node("C",15,20)) 
    AddNode(G, Node("D",18,15)) 
    AddNode(G, Node("E",2,4)) 
    AddNode(G, Node("F",6,5)) 
    AddNode(G, Node("G",12,12)) 
    AddNode(G, Node("H",10,3)) 
    AddNode(G, Node("I",19,1)) 
    AddNode(G, Node("J",13,5)) 
    AddNode(G, Node("K",3,15)) 
    AddNode(G, Node("L",4,10)) 
    AddSegment(G, "A","B") 
    AddSegment(G, "A","E") 
    AddSegment(G, "A","K") 
    AddSegment(G, "B","A") 
    AddSegment(G, "B","C") 
    AddSegment(G, "B","F") 
    AddSegment(G, "B","K") 
    AddSegment(G, "B","G") 
    AddSegment(G, "C","D") 
    AddSegment(G, "C","G") 
    AddSegment(G, "D","G") 
    AddSegment(G, "D","H") 
    AddSegment(G, "D","I") 
    AddSegment(G, "E","F") 
    AddSegment(G, "F","L") 
    AddSegment(G, "G","B") 
    AddSegment(G, "G","F") 
    AddSegment(G, "G","H") 
    AddSegment(G, "I","D") 
    AddSegment(G, "I","J") 
    AddSegment(G, "J","I") 
    AddSegment(G, "K","A") 
    AddSegment(G, "K","L") 
    AddSegment(G, "L","K") 
    AddSegment(G, "L","F") 
    return G 
def CreateGraph_2 (): 
    G = Graph() 
    AddNode(G, Node("A",4,1))
    AddNode(G, Node("B",6,4)) 
    AddNode(G, Node("C",5,7)) 
    AddNode(G, Node("D",4,6)) 
    AddNode(G, Node("E",3,7))
    AddNode(G, Node("F",2,4)) 
    AddSegment(G, "A","B") 
    AddSegment(G, "B","C")
    AddSegment(G, "C","D")
    AddSegment(G, "D","E")
    AddSegment(G, "E","F")
    AddSegment(G, "F","A")
    return G

print ("Probando el grafo...") 
G = CreateGraph_1 ()
J = CreateGraph_2()
fig, axes = plt.subplots(2, 3, figsize=(12, 6))
Plot(G,axes[0][0]) 
PlotNode(G, "C",axes[1][0])
SaveGraph(G,'Proyecto/graph_data.txt')
Plot(J,axes[0][1]) 
PlotNode(J, "A",axes[1][1])
SaveGraph(J,'Proyecto/graph_prueba.txt')
plt.show()
n = GetClosest(G,15,5) 
print (n.name) # La respuesta debe ser J 
n = GetClosest(G,8,19)  
print (n.name) # La respuesta debe ser B